# Generated by Django 2.1.7 on 2019-05-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
